export const templateData = {
  resumeId: null,
  title: '我的简历',
  template: null,
  guideId: null,
  modules: [
    {
      id: null,
      moduleKey: 'BASIC',
      moduleName: '基础信息',
      builtIn: 1,
      hidden: 0,
      sortOrder: 0,
      items: [
        {
          id: null,
          itemName: '基础信息',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'BASIC_GENDER', fieldLabel: '性别', fieldType: 'SELECT', fieldValue: '男', builtIn: 1, hidden: 0, sortOrder: 0, fieldOptions: ['男', '女'] },
            { id: null, fieldKey: 'BASIC_BIRTHDAY', fieldLabel: '出生年月', fieldType: 'DATE', fieldValue: '1998-08', builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'BASIC_EMAIL', fieldLabel: '邮箱', fieldType: 'STRING', fieldValue: '1540979440@qq.com', builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'BASIC_PHONE', fieldLabel: '手机号', fieldType: 'STRING', fieldValue: '18342210410', builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'BASIC_ETHNICITY', fieldLabel: '民族', fieldType: 'STRING', fieldValue: '汉', builtIn: 1, hidden: 1, sortOrder: 2 },
            { id: null, fieldKey: 'BASIC_HOMETOWN', fieldLabel: '籍贯', fieldType: 'STRING', fieldValue: '辽宁铁岭', builtIn: 1, hidden: 1, sortOrder: 3 },
            { id: null, fieldKey: 'BASIC_POLITICAL_STATUS', fieldLabel: '政治面貌', fieldType: 'STRING', fieldValue: '党员', builtIn: 1, hidden: 1, sortOrder: 4 },
            { id: null, fieldKey: 'BASIC_ADDRESS', fieldLabel: '通信地址', fieldType: 'STRING', fieldValue: '辽宁省大连市甘井子区', builtIn: 1, hidden: 1, sortOrder: 5 },
            { id: null, fieldKey: 'BASIC_JOB_STATUS', fieldLabel: '求职状态', fieldType: 'STRING', fieldValue: '在职', builtIn: 1, hidden: 0, sortOrder: 6 },
            { id: null, fieldKey: 'BASIC_EXPECTED_POSITION', fieldLabel: '期望岗位', fieldType: 'STRING', fieldValue: '前端开发', builtIn: 1, hidden: 1, sortOrder: 7 },
            { id: null, fieldKey: 'BASIC_EXPECTED_CITY', fieldLabel: '期望城市', fieldType: 'STRING', fieldValue: '大连', builtIn: 1, hidden: 0, sortOrder: 8 },
            { id: null, fieldKey: 'BASIC_EXPECTED_SALARY', fieldLabel: '期望薪资', fieldType: 'STRING', fieldValue: '面议', builtIn: 1, hidden: 0, sortOrder: 9 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'EDUCATION',
      moduleName: '教育经历',
      builtIn: 1,
      hidden: 0,
      sortOrder: 1,
      items: [
        {
          id: null,
          itemName: '教育经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'EDUCATION_SCHOOL_NAME', fieldLabel: '学校名称', fieldType: 'STRING', fieldValue: '大连航运职业技术学院', builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'EDUCATION_DEGREE', fieldLabel: '学历', fieldType: 'STRING', fieldValue: '大专', builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'EDUCATION_MAJOR', fieldLabel: '专业名称', fieldType: 'STRING', fieldValue: '船舶机械工程技术', builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'EDUCATION_START_TIME', fieldLabel: '教育时间段', fieldType: 'DATERANGE', fieldValue: '2024-09 至 2028-06', builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'EDUCATION_DESCRIPTION', fieldLabel: '描述', fieldType: 'RICH_TEXT', fieldValue: '描述描述描述描述描述', builtIn: 1, hidden: 0, sortOrder: 5 },
          ],
        },
        {
          id: null,
          itemName: '教育经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'EDUCATION_SCHOOL_NAME', fieldLabel: '学校名称', fieldType: 'STRING', fieldValue: '大连航运职业技术学院', builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'EDUCATION_DEGREE', fieldLabel: '学历', fieldType: 'STRING', fieldValue: '大专', builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'EDUCATION_MAJOR', fieldLabel: '专业名称', fieldType: 'STRING', fieldValue: '船舶机械工程技术', builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'EDUCATION_START_TIME', fieldLabel: '教育时间段', fieldType: 'DATERANGE', fieldValue: '2024-09 至 2028-06', builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'EDUCATION_DESCRIPTION', fieldLabel: '描述', fieldType: 'RICH_TEXT', fieldValue: '描述描述描述描述描述', builtIn: 1, hidden: 0, sortOrder: 5 },
          ],
        },
             {
          id: null,
          itemName: '教育经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'EDUCATION_SCHOOL_NAME', fieldLabel: '学校名称', fieldType: 'STRING', fieldValue: '大连航运职业技术学院', builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'EDUCATION_DEGREE', fieldLabel: '学历', fieldType: 'STRING', fieldValue: '大专', builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'EDUCATION_MAJOR', fieldLabel: '专业名称', fieldType: 'STRING', fieldValue: '船舶机械工程技术', builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'EDUCATION_START_TIME', fieldLabel: '教育时间段', fieldType: 'DATERANGE', fieldValue: '2024-09 至 2028-06', builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'EDUCATION_DESCRIPTION', fieldLabel: '描述', fieldType: 'RICH_TEXT', fieldValue: '描述描述描述描述描述', builtIn: 1, hidden: 0, sortOrder: 5 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'WORK',
      moduleName: '工作经历',
      builtIn: 1,
      hidden: 0,
      sortOrder: 2,
      items: [
        {
          id: null,
          itemName: '工作经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'WORK_COMPANY_NAME', fieldLabel: '公司名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'WORK_POSITION', fieldLabel: '岗位名', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'WORK_START_TIME', fieldLabel: '工作时间段', fieldType: 'DATERANGE', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'WORK_DESCRIPTION', fieldLabel: '工作描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 4 },
          ],
        },

        {
          id: null,
          itemName: '工作经历2',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'WORK_COMPANY_NAME', fieldLabel: '公司名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'WORK_POSITION', fieldLabel: '岗位名', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'WORK_START_TIME', fieldLabel: '工作时间段', fieldType: 'DATERANGE', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'WORK_DESCRIPTION', fieldLabel: '工作描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 4 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'PROJECT',
      moduleName: '项目经历',
      builtIn: 1,
      hidden: 0,
      sortOrder: 3,
      items: [
        {
          id: null,
          itemName: '项目经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'PROJECT_NAME', fieldLabel: '项目名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'PROJECT_RELATED_COMPANY', fieldLabel: '关联公司', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'PROJECT_END_TIME', fieldLabel: '项目时间段', fieldType: 'DATERANGE', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'PROJECT_DESCRIPTION', fieldLabel: '项目描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 4 },
            { id: null, fieldKey: 'PROJECT_ACHIEVEMENT', fieldLabel: '项目业绩', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 5 },
          ],
        },
        {
          id: null,
          itemName: '项目经历2',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'PROJECT_NAME', fieldLabel: '项目名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'PROJECT_RELATED_COMPANY', fieldLabel: '关联公司', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'PROJECT_END_TIME', fieldLabel: '项目时间段', fieldType: 'DATERANGE', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'PROJECT_DESCRIPTION', fieldLabel: '项目描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 4 },
            { id: null, fieldKey: 'PROJECT_ACHIEVEMENT', fieldLabel: '项目业绩', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 5 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'STRENGTH',
      moduleName: '个人优势',
      builtIn: 1,
      hidden: 0,
      sortOrder: 4,
      items: [
        {
          id: null,
          itemName: '个人优势',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'STRENGTH_CONTENT', fieldLabel: '个人优势描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'SKILL',
      moduleName: '技能',
      builtIn: 1,
      hidden: 0,
      sortOrder: 5,
      items: [
        {
          id: null,
          itemName: '技能',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'SKILL_CONTENT', fieldLabel: '技能描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'INTERNSHIP',
      moduleName: '实习经历',
      builtIn: 1,
      hidden: 1,
      sortOrder: 6,
      items: [
        {
          id: null,
          itemName: '实习经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'INTERNSHIP_COMPANY_NAME', fieldLabel: '公司名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'INTERNSHIP_POSITION', fieldLabel: '岗位名', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'INTERNSHIP_START_TIME', fieldLabel: '实习时间段', fieldType: 'DATERANGE', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'INTERNSHIP_DESCRIPTION', fieldLabel: '实习描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 4 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'CAMPUS',
      moduleName: '校园经历',
      builtIn: 1,
      hidden: 1,
      sortOrder: 7,
      items: [
        {
          id: null,
          itemName: '校园经历1',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'CAMPUS_SCHOOL_NAME', fieldLabel: '学校名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
            { id: null, fieldKey: 'CAMPUS_ORGANIZATION', fieldLabel: '组织名称', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 1 },
            { id: null, fieldKey: 'CAMPUS_POSITION', fieldLabel: '岗位名', fieldType: 'STRING', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 2 },
            { id: null, fieldKey: 'CAMPUS_START_TIME', fieldLabel: '校园时间段', fieldType: 'DATERANGE', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 3 },
            { id: null, fieldKey: 'CAMPUS_DESCRIPTION', fieldLabel: '校园描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 5 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'CERTIFICATE',
      moduleName: '证书',
      builtIn: 1,
      hidden: 1,
      width: '100%',
      dataType: 'mergeable',
      sortOrder: 8,
      items: [
        {
          id: null,
          itemName: '证书',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'CERTIFICATE_CONTENT', fieldLabel: '证书描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'AWARD',
      moduleName: '获奖',
      builtIn: 1,
      hidden: 1,
      width: '100%',
      dataType: 'mergeable',
      sortOrder: 9,
      items: [
        {
          id: null,
          itemName: '获奖',
          builtIn: 1,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'AWARD_CONTENT', fieldLabel: '奖项描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 1, hidden: 0, sortOrder: 0 },
          ],
        },
      ],
    },
    {
      id: null,
      moduleKey: 'CUSTOM',
      moduleName: '自定义模块',
      builtIn: 0,
      hidden: 0,
      sortOrder: 10,
      items: [
        {
          id: null,
          itemName: '自定义模块',
          builtIn: 0,
          hidden: 0,
          sortOrder: 0,
          fields: [
            { id: null, fieldKey: 'CUSTOM_CONTENT', fieldLabel: '自定义描述', fieldType: 'RICH_TEXT', fieldValue: null, builtIn: 0, hidden: 0, sortOrder: 0 },
          ],
        },
      ],
    },
  ],
}
